Marked removal of unittest2 as new feature.
It causes an error in Plone 4.3 when using Python 2.6:

Error in test test_redirect_to_uuid_invalid_uuid (plone.app.uuid.tests.FunctionalTestCase)
Traceback (most recent call last):
  File "/usr/local/pythons/parts/opt/lib/python2.6/unittest.py", line 279, in run
    testMethod()
  File "/Users/maurits/community/plone-coredev/4.3/src/plone.app.uuid/plone/app/uuid/tests.py", line 175, in test_redirect_to_uuid_invalid_uuid
    with self.assertRaises(NotFound):
TypeError: failUnlessRaises() takes at least 3 arguments (2 given)

So I will create a new branch to use on 4.3.

[ci skip]